### ISSUE TITLE
[JAVA] API REST Gestión de proveedores

### ISSUE THREAD

**Issue by damianfanaro** [igrowker/i002-donatello-back-java#6]
Implementar los siguientes endpoints:

- GET /api/providers
- POST /api/providers
- PUT /api/providers/{id}
- DELETE /api/providers/{id}

**Comment by EmaMaga** [comment]
La rama ya está terminada en su totalidad, solo falta la ID_User(FK) debido que la entidad todavía no se encuentra, lo demás ya está.
